import { Link } from "@tanstack/react-router";
import { motion } from "motion/react";
import { ArrowRight } from "lucide-react";
import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";

export function Reveal({children, delay=0, className=""}:{children:ReactNode;delay?:number;className?:string}) { return <motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.55,delay,ease:[.2,.7,.2,1]}}>{children}</motion.div>; }

export function Hero({image,eyebrow,title,description,children,full=false}:{image:string;eyebrow:string;title:string;description:string;children?:ReactNode;full?:boolean}) { return <section className={`relative isolate overflow-hidden ${full?'min-h-[92svh]':'min-h-[66svh]'} flex items-end`}><img src={image} width={1536} height={1024} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,color-mix(in_oklab,var(--primary-dark)_94%,transparent)_0%,color-mix(in_oklab,var(--primary-dark)_74%,transparent)_48%,color-mix(in_oklab,var(--primary-dark)_20%,transparent)_100%)]"/><div className="container-wide pb-16 pt-36 sm:pb-20"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="max-w-4xl text-hero-foreground"><p className="mb-5 text-sm font-semibold uppercase tracking-widest text-hero-foreground/75">{eyebrow}</p><h1 className="max-w-4xl text-5xl font-bold leading-[1.02] sm:text-6xl lg:text-8xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-hero-foreground/80 sm:text-lg">{description}</p>{children&&<div className="mt-9 flex flex-wrap gap-3">{children}</div>}</motion.div></div></section>; }

export function SectionHeading({eyebrow,title,text,light=false}:{eyebrow:string;title:string;text?:string;light?:boolean}) { return <div className="max-w-3xl"><p className={`text-sm font-semibold uppercase tracking-widest ${light?'text-primary-foreground/65':'text-highlight'}`}>{eyebrow}</p><h2 className={`mt-4 text-4xl font-bold leading-tight sm:text-5xl ${light?'text-primary-foreground':''}`}>{title}</h2>{text&&<p className={`mt-5 max-w-2xl leading-7 ${light?'text-primary-foreground/70':'text-muted-foreground'}`}>{text}</p>}</div>; }

export function CtaBand({title,text}:{title:string;text:string}) { return <section className="bg-primary-dark py-16 text-primary-foreground"><div className="container-wide grid items-end gap-8 md:grid-cols-[1fr_auto]"><div><h2 className="max-w-3xl text-4xl font-bold sm:text-5xl">{title}</h2><p className="mt-4 max-w-xl text-primary-foreground/70">{text}</p></div><Button asChild variant="cta" size="lg"><Link to="/devis">Demander un devis <ArrowRight/></Link></Button></div></section>; }

export function ProductCard({product}:{product:(typeof import('./site-data').products)[number]}) { return <article className="group overflow-hidden rounded-lg bg-card shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><Link to="/produits" className="block"><div className="overflow-hidden"><img src={product.image} width={1536} height={1024} loading="lazy" alt={`${product.title} fabriqués par LGM`} className="aspect-[4/3] w-full object-cover image-hover group-hover:scale-105"/></div><div className="p-6"><h3 className="text-xl font-semibold">{product.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{product.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Explorer <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></div></Link></article>; }